bilangan_pertama = float(input("Masukkan bilangan pertama: "))
bilangan_kedua = float(input("Masukkan bilangan kedua: "))

hasil_penjumlahan = bilangan_pertama + bilangan_kedua
hasil_pengurangan = bilangan_pertama - bilangan_kedua
hasil_modulus = bilangan_pertama % bilangan_kedua

print("Hasil penjumlahan:", hasil_penjumlahan)
print("Hasil pengurangan:", hasil_pengurangan)
print("Hasil modulus:", hasil_modulus)